Pep8
arcoslab/face-eyes pull request #2
Opened 2018-03-14 19:35 UTC by BRJMM

2018-03-15 02:44 UTC, degv364 requested changes
According to PEP8 function names should be in lowercase.

2018-03-15 02:44 UTC, degv364 commented on eyes-servo-tes.py
>  def print_conEye(strip):
Functions are all lower case

2018-03-15 02:44 UTC, degv364 commented on eyes-servo-tes.py
>  def print_surEye(strip):
Lower case plase

2018-03-15 02:44 UTC, degv364 commented on eyes-servo-tes.py
>  def print_sadEye(strip):
lower case please

2018-03-15 02:44 UTC, degv364 commented on eyes-servo-tes.py
>  def print_hapEye(strip):
lower case please

2018-03-15 02:44 UTC, degv364 commented on eyes-servo-tes.py
>  def print_calEye(strip):
lower case please

2018-03-15 02:44 UTC, degv364 commented on eyes-servo-tes.py
>  def print_eneEye(strip):
lowercase please

2018-03-15 02:44 UTC, degv364 commented on eyes-servo-tes.py
>  def colorWipe(strip, color, wait_ms=50):
lowercase please

2018-03-25 03:34 UTC, BRJMM commented
changes made

2018-03-25 03:49 UTC, degv364 approved these changes

2018-03-25 03:49 UTC, degv364 commented
Looks good to me. But lets wiat for another reviewer to approve.

2018-03-25 03:53 UTC, BRJMM commented
I will wait the another approve to continue

2018-03-25 19:25 UTC, merged

2018-03-25 19:25 UTC, jcrono commented
Changed merged, thanks!